# conda env create -f environment.yml
name: xopt-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - deap
  - numpy
  - pydantic
  - pyyaml
  - pandas
  - pyepics
  - ipywidgets
  - tqdm
# parallel
  - mpi4py
  - dask
# Developer
  - pytest
  - jupyterlab>=3
  - matplotlib
  - pygments
  - numdifftools
  - pip
  - pip:
    - torch>=1.10.2
    - gpytorch
    - botorch
