# conda env create -f environment.yml
name: xopt-dev
channels:
  - conda-forge
dependencies:
  - python=3.7
  - deap
  - numpy
  - pydantic
  - pyyaml
  - pytorch>=1.10.2
  - botorch
  - gpytorch
  - pandas
  - ipywidgets
  - tqdm
# parallel
  - mpi4py
  - dask
# Developer
  - pytest
  - jupyterlab>=3
  - matplotlib
  - pygments
  - matplotlib
  - pyepics
  - numdifftools
  - pip